openapi: 3.0.1
info:
  title: MCP Weather Tools
  description: Tools for weather alerts and forecasts
  version: 1.0.0
servers:
  - url: https://mcpserverpocbhn.azurewebsites.net/
paths:
  /mcp/stream:
    post:
      summary: MCP Stream Endpoint
      operationId: mcpStream
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jsonrpc:
                  type: string
                id:
                  type: integer
                method:
                  type: string
                params:
                  type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
